import { useEffect, useMemo, useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { useAppStore } from '../../store'
import { useT } from '../../i18n'
import * as api from '../../api'
import { sortByRice } from '../../lib/rice'
import SectionHeader from '../ui/SectionHeader'
import ScorePill from '../ui/ScorePill'
import { Sparkle, Doc, Copy, Link, Check } from '../ui/Icons'

export default function SummaryScreen() {
  const {
    language, clusters, summaryContent, prdContent, streaming, feedbackList, sessionId,
    setStep, setSessionId, stopGeneration,
  } = useAppStore()
  const t = useT(language)
  const [copied, setCopied] = useState(false)
  const [shareDone, setShareDone] = useState(false)

  const sorted = useMemo(() => sortByRice(clusters ?? []), [clusters])
  const top3 = sorted.slice(0, 3)

  // Auto-save when streaming completes
  useEffect(() => {
    if (!streaming && summaryContent && clusters) {
      api.saveSession({
        language, step: 'summary', feedback_list: feedbackList,
        clusters, summary_content: summaryContent, session_id: sessionId,
      }).then(setSessionId).catch(() => {})
    }
  }, [streaming])

  if (!summaryContent || !clusters) return null

  const handleShare = () => {
    if (!sessionId) return
    const url = `${window.location.origin}/?session=${sessionId}&share=1&type=summary`
    navigator.clipboard.writeText(url).then(() => {
      setShareDone(true)
      setTimeout(() => setShareDone(false), 2000)
    })
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summaryContent ?? '')
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {}
  }

  const riceLabels = language === 'ru'
    ? { r: 'Охват', i: 'Влияние', c: 'Уверен.', e: 'Усилия' }
    : { r: 'Reach', i: 'Impact',  c: 'Conf.',   e: 'Effort' }

  return (
    <div className="h-full flex flex-col">
      <SectionHeader
        eyebrow={`step 05 · ${language === 'ru' ? 'сгенерировано агентом' : 'generated by agent'}`}
        title={t('summary_title')}
        subtitle={streaming ? t('prd_sub_streaming') : t('summary_sub_done')}
        actions={
          <>
            {streaming && (
              <button
                className="btn-primary btn-sm gap-1"
                onClick={stopGeneration}
              >
                {t('stop')}
              </button>
            )}
            <button
              className="btn btn-sm gap-1"
              disabled={streaming || !sessionId}
              onClick={handleShare}
            >
              {shareDone
                ? <><Check size={12} /> {language === 'ru' ? 'Скопировано!' : 'Copied!'}</>
                : <><Link size={12} /> {language === 'ru' ? 'Поделиться' : 'Share'}</>}
            </button>
            <button
              className="btn btn-sm gap-1"
              disabled={!prdContent}
              onClick={() => setStep('prd')}
            >
              <Doc size={13} /> {t('full_prd')}
            </button>
            <button className="btn btn-sm" onClick={() => setStep('rice')}>
              {language === 'ru' ? 'Назад' : 'Back'}
            </button>
          </>
        }
      />

      <div
        className="flex-1 min-h-0 overflow-hidden grid"
        style={{ gridTemplateColumns: '1fr 300px' }}
      >
        {/* Left: markdown content */}
        <div className="overflow-y-auto px-10 py-8">
          <article className="max-w-[680px] mx-auto">
            <div className="prose-prd">
              <ReactMarkdown remarkPlugins={[remarkGfm]}>{summaryContent}</ReactMarkdown>
            </div>
            {streaming && <span className="stream-caret" />}
          </article>
        </div>

        {/* Right: top-3 clusters + actions */}
        <aside className="border-l border-neutral-200 dark:border-neutral-800 overflow-y-auto p-4 bg-white dark:bg-neutral-900 flex flex-col gap-4">
          {/* Top-3 cluster cards */}
          <div>
            <div className="eyebrow mb-2">{t('top3_cards')}</div>
            <div className="flex flex-col gap-2">
              {top3.map((c, i) => (
                <div
                  key={c.id}
                  className="rounded-lg border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-800/50 p-3"
                >
                  <div className="flex items-start gap-2.5 mb-2">
                    <span className="font-mono text-[10px] font-bold text-neutral-400 bg-neutral-200 dark:bg-neutral-700 rounded px-1.5 py-0.5 shrink-0 mt-0.5">
                      #{i + 1}
                    </span>
                    <span className="text-[12.5px] font-medium text-ink dark:text-neutral-100 leading-[1.35] flex-1">
                      {c.name}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex gap-2 font-mono text-[10.5px] text-neutral-500 dark:text-neutral-400">
                      <span>{riceLabels.r} {c.rice.reach}</span>
                      <span>{riceLabels.i} {c.rice.impact}</span>
                      <span>{riceLabels.c} {c.rice.confidence}%</span>
                      <span>{riceLabels.e} {c.rice.effort}</span>
                    </div>
                    <ScorePill score={c.rice_score} size="sm" />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="border-t border-neutral-200 dark:border-neutral-800" />

          {/* Actions */}
          <div className="flex flex-col gap-2">
            <button
              className="btn btn-sm gap-1.5 w-full justify-center opacity-50 cursor-not-allowed"
              disabled
              title={language === 'ru' ? 'Скоро' : 'Coming soon'}
            >
              <Sparkle size={13} />
              {t('send_to_slack')}
            </button>
            <button
              className="btn btn-sm gap-1.5 w-full justify-center"
              disabled={streaming}
              onClick={handleCopy}
            >
              <Copy size={13} />
              {copied
                ? (language === 'ru' ? 'Скопировано!' : 'Copied!')
                : t('copy_md')}
            </button>
          </div>

          <div className="border-t border-neutral-200 dark:border-neutral-800" />

          {/* Word count info */}
          <div className="text-[11.5px] text-neutral-400 dark:text-neutral-500 font-mono">
            {(summaryContent ?? '').split(/\s+/).filter(Boolean).length}{' '}
            {language === 'ru' ? 'слов' : 'words'}
            {' · '}
            {top3.length}{' '}
            {language === 'ru' ? 'кластеров' : 'clusters'}
          </div>
        </aside>
      </div>
    </div>
  )
}
